db:
  name: mydatabase
  table: mytassbleee
  user: admin
  password: secret
  host: localhost
  port: 5432

ollama:
  model: llama3.3:70b-instruct-q2_K

embedding:
  model: Linq-AI-Research/Linq-Embed-Mistral
  dimensions: 4096

data:
  folder: ./data/repos/kiali-master
  extensions: #.csv .docx .epub .hwp .ipynb .jpeg, .jpg .mbox .md .mp3, .mp4 .pdf .png .ppt, .pptm, .pptx (no .json)
    - .md
