db:
  name: mydatabase
  table: books
  user: admin
  password: secret
  host: localhost
  port: 5432

ollama:
  model: deepseek-r1:8b-llama-distill-fp16
  temperature: 0.2

embedding:
  model: mxbai-embed-large:latest
  dimensions: 1024

data:
  folder: ./data/books/
  extensions: #.csv .docx .epub .hwp .ipynb .jpeg, .jpg .mbox .md .mp3, .mp4 .pdf .png .ppt, .pptm, .pptx (no .json)
    - .md
