db:
  name: mydatabase
  table: llamaindex
  user: admin
  password: secret
  host: localhost
  port: 5432

ollama:
  model: granite3.3:latest
  temperature: 0.2

embedding:
  model: mxbai-embed-large:latest
  dimensions: 1024

data:
  folder: ./data/repos/llama_index
  extensions: #.csv .docx .epub .hwp .ipynb .jpeg, .jpg .mbox .md .mp3, .mp4 .pdf .png .ppt, .pptm, .pptx (no .json)
    - .md
